image: mgjm/rust-ci

stages:
  - test
  - build

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo
  RUSTFLAGS: -D warnings

test:
  stage: test
  script:
    - rustc --version
    - cargo --version
    - cargo test --verbose

clippy:
  stage: test
  script:
    - cargo clippy

rustfmt:
  stage: test
  cache: {}
  script:
    - cargo fmt -- --check

pages:
  stage: build
  script:
    - cargo doc --no-deps
    - mv target/doc public
    - echo '<meta http-equiv="refresh" content="0; url=prellblock">' > public/index.html
  artifacts:
    paths:
      - public

release-build:
  stage: build
  script:
    - cargo build --release -Z unstable-options --out-dir release
  artifacts:
    paths:
      - release

cache:
  key: $CI_JOB_NAME
  paths:
    - cargo/
    - target/
