[workspace]
members = [
    "trdp-rs",
    "connection",
    "hello_world",
    "balise",
    "genesis-wizard",
    "pinxit",
    "prellblock",
    "prellblock-client",
    "prellblock-client-api",
]
