[workspace]
members = [
    "balise",
    "pinxit",
    "prellblock",
    "prellblock-client",
    "prellblock-client-api",
]

[patch.crates-io]
newtype-enum = { path = "../newtype-enum/newtype-enum" }
newtype-enum-macro = { path = "../newtype-enum/newtype-enum-macro" }
