version: "3.3"

services:
    alice:
        command: config/alice/alice.toml config/genesis/genesis.yaml
        build: .
        volumes:
            - "./config:/prellblock/config"
            - "./blocks:/prellblock/blocks"
        networks:
            prellblock_net:
                ipv4_address: 172.28.0.10
    bob:
        command: config/bob/bob.toml config/genesis/genesis.yaml
        build: .
        volumes:
            - "./config:/prellblock/config"
            - "./blocks:/prellblock/blocks"
        environment:
            - RUST_LOG=prellblock::batcher=trace
        networks:
            prellblock_net:
                ipv4_address: 172.28.0.11
    carol:
        command: config/carol/carol.toml config/genesis/genesis.yaml
        build: .
        volumes:
            - "./config:/prellblock/config"
            - "./blocks:/prellblock/blocks"
        networks:
            prellblock_net:
                ipv4_address: 172.28.0.12
    dave:
        command: config/dave/dave.toml config/genesis/genesis.yaml
        build: .
        volumes:
            - "./config:/prellblock/config"
            - "./blocks:/prellblock/blocks"
        networks:
            prellblock_net:
                ipv4_address: 172.28.0.13
    frank:
        command: config/frank/frank.toml config/genesis/genesis.yaml
        build: .
        volumes:
            - "./config:/prellblock/config"
            - "./blocks:/prellblock/blocks"
        networks:
            prellblock_net:
                ipv4_address: 172.28.0.14

    heidi:
        command: config/heidi/heidi.toml config/genesis/genesis.yaml
        build: .
        volumes:
            - "./config:/prellblock/config"
            - "./blocks:/prellblock/blocks"
        networks:
            prellblock_net:
                ipv4_address: 172.28.0.15

    ivan:
        command: config/ivan/ivan.toml config/genesis/genesis.yaml
        build: .
        volumes:
            - "./config:/prellblock/config"
            - "./blocks:/prellblock/blocks"
        environment: 
            - RUST_LOG=prellblock::consensus=trace
        networks:
            prellblock_net:
                ipv4_address: 172.28.0.16

    prometheus:
        image: prom/prometheus
        volumes:
            - ./benchmarking/prometheus/config:/prometheus
            - ./benchmarking/prometheus/data/prometheus:/data
        command:
            - '--config.file=/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/tmp/data'
        ports:
            - 9090:9090
        restart: unless-stopped
        networks: 
            prellblock_net:

    grafana:
        image: grafana/grafana:latest
        restart: unless-stopped
        depends_on:
            - prometheus
        ports:
            - "3000:3000"
        volumes:
            - ./benchmarking/grafana/config/grafana.ini:/etc/grafana/grafana.ini
            - ./benchmarking/grafana/config/datasources:/etc/grafana/provisioning/datasources/
            - ./benchmarking/grafana/config/dashboards:/etc/grafana/provisioning/dashboards/
            - ./benchmarking/grafana/data/grafana:/var/lib/grafana
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=prellblock
            - GF_USERS_ALLOW_SIGN_UP=false
        networks: 
            prellblock_net:

networks:
    prellblock_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16
