identity = "./config/emily/emily.key"
tls_id = "./certificates/emily/emily.pfx"
block_path = "./blocks/emily"
data_path = "./data/emily"
turi_address = "127.0.0.1:3130"
peer_address = "127.0.0.1:2480"
