256cdb0197402705f96d39eab7dd3d47a39cb75673a58852d83f666973d80e01:
  name: TestClientCLI
  # is_rpu: false
  # expire_at: 2020-04-15T10:04:59.300878700Z
  writing_rights: true
  # reading_rights:
  #   - accounts:
  #       whitelist:
  #         permissions:
  #           - scope: Emily
  #     namespace:
  #       blacklist:
  #         permissions:
  #           - scope: speed
