[[rpu]]
name = "emily"
peer_id = "./config/emily/emily.pub"
peer_address = "172.20.5.10:2480"
turi_address = "172.20.5.10:3130"

[[rpu]]
name = "james"
peer_id = "./config/james/james.pub"
peer_address = "172.20.5.12:2480"
turi_address = "172.20.5.12:3130"

[[rpu]]
name = "percy"
peer_id = "./config/percy/percy.pub"
peer_address = "172.20.5.13:2480"
turi_address = "172.20.5.13:3130"

[[rpu]]
name = "thomas"
peer_id = "./config/thomas/thomas.pub"
peer_address = "172.20.5.14:2480"
turi_address = "172.20.5.14:3130"
