[[rpu]]
name = "emily"
peer_id = "./config/emily/emily.pub"
peer_address = "127.0.0.1:2480"
turi_address = "127.0.0.1:3130"
monitoring_address = "127.0.0.1:9091"

[[rpu]]
name = "james"
peer_id = "./config/james/james.pub"
peer_address = "127.0.0.1:2481"
turi_address = "127.0.0.1:3131"
monitoring_address = "127.0.0.1:9092"

[[rpu]]
name = "percy"
peer_id = "./config/percy/percy.pub"
peer_address = "127.0.0.1:2482"
turi_address = "127.0.0.1:3132"
monitoring_address = "127.0.0.1:9093"

[[rpu]]
name = "thomas"
peer_id = "./config/thomas/thomas.pub"
peer_address = "127.0.0.1:2483"
turi_address = "127.0.0.1:3133"
monitoring_address = "127.0.0.1:9094"
