type: admin
expire_at: #never
  at_date: 2020-06-15T10:04:59.300878700Z
has_writing_rights: false
reading_rights:
  - accounts:
      whitelist:
        - scope: Emily
    namespace:
      blacklist:
        - scope: speed
  - accounts:
      whitelist:
        - scope: Thomas
    namespace:
      blacklist:
        - scope: speed
