[package]
name = "prellblock"
version = "0.1.0"
authors = [
    "Benedikt Schenkel <benedikt.schenkel@student.hpi.de>",
    "Felix Gohla <felix.gohla@student.hpi.de>",
    "Malte Andersch <malte.andersch@student.hpi.de>",
    "Martin Michaelis <code@mgjm.de>",
]
edition = "2018"

[dependencies]
balise = { path = "../balise", features = ["server", "client", "tls"] }
blake2 = "0.8.1"
blocksberg = { path = "../blocksberg" }
chrono = "0.4.11"
err-derive = "0.2.3"
lazy_static = "1.4.0"
log = "0.4.8"
pinxit = { path = "../pinxit" }
prellblock-client-api = { path = "../prellblock-client-api" }
pretty_env_logger = "0.4.0"
serde = { version = "1.0.105", features = ["derive"] }
serde_json = "1.0.51"
sled = { version = "0.31.0", features = ["compression"] }
structopt = "0.3.12"
toml = "0.5.6"
bincode = "1.2.1"
