[package]
name = "prellblock"
version = "0.1.0"
authors = [
    "Benedikt Schenkel <benedikt.schenkel@student.hpi.de>",
    "Felix Gohla <felix.gohla@student.hpi.de>",
    "Malte Andersch <malte.andersch@student.hpi.de>",
    "Martin Michaelis <code@mgjm.de>",
]
edition = "2018"

[dependencies]
log = "0.4.8"
pretty_env_logger = "0.4.0"
serde = { version = "1.0.105", features = ["derive"] }
structopt = "0.3.12"
lazy_static = "1.4.0"
balise = { path = "../balise", features = ["server", "client", "tls"] }
prellblock-client-api = { path = "../prellblock-client-api" }
toml = "0.5.6"
